### ISSUE TITLE
It renders blank screen

### ISSUE THREAD

**Issue by anishagg17** [WormBase/website-public#12]
It renders blank screen not the content of the website 

![Screenshot 2020-03-06 at 5 01 00 PM](https://user-images.githubusercontent.com/43617894/76080046-10ea9e80-5fcc-11ea-9c1c-dc810e5fce0f.png)

**Comment by anishagg17** [comment]
@sibyl229 
```
I have set catlyst_port to 4040
and webpack_port to 8080
```
before running `make local` command

**Comment by sibyl229** [comment]
@anishagg17 Thanks for submitting the issue. I will clarify this in the README. 

**Please connect your browser to the catalyst port** instead of the webpack port. 

This stack **isn't** a single page application. In other words, it isn't a webpackDevServer with a proxy to REST API. It's a Model-View-Controller with server-side rendered pages, and React is used to render certain portion of a page (particularly visualizations).
